// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workspaces.Data;

#nullable disable

namespace Workspaces.Migrations
{
    [DbContext(typeof(WorkspacesDbContext))]
    [Migration("20240125150220_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workspaces.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 1,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 2,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 3,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 4,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 5,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 6,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 7,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 8,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 9,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 10,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 11,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 12,
                            WorkspaceId = 3
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 13,
                            WorkspaceId = 3
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 14,
                            WorkspaceId = 3
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = 15,
                            WorkspaceId = 3
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 1,
                            WorkspaceId = 4
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 2,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 3,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 4,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 5,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 6,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 7,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 8,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 9,
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 10,
                            WorkspaceId = 3
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 11,
                            WorkspaceId = 3
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 12,
                            WorkspaceId = 4
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 13,
                            WorkspaceId = 4
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 14,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = 15,
                            WorkspaceId = 3
                        });
                });

            modelBuilder.Entity("Workspaces.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mr. Boss",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zooroid Madshine",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bodori Hoborider",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fluffbuns Wigglesniff",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chewaboo Droopyseed",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beaniebs Boombag",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bittyitt HippyFadden",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dingspitz Woolham",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Humlu Madborn",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 10,
                            Name = "Weewax Pieham",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "Figman Wigglebrain",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "Binwee Sockhill",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "Beaniepants Beaniegold",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "Figby Madson",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "Jambo Messyman",
                            TeamId = 5
                        });
                });

            modelBuilder.Entity("Workspaces.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Leadership"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Managers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Support"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Developers"
                        });
                });

            modelBuilder.Entity("Workspaces.Models.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            Name = "10th Floor Office"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Name = "Ground Floor Room"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 20,
                            Name = "Basement"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = -1,
                            Name = "Home Office"
                        });
                });

            modelBuilder.Entity("Workspaces.Models.Assignment", b =>
                {
                    b.HasOne("Workspaces.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workspaces.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Workspaces.Models.Employee", b =>
                {
                    b.HasOne("Workspaces.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
